#!/bin/bash

# تغيير الدليل إلى موقع السكربت
cd $(cd $(dirname $0); pwd)

echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'

echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'

read Install

case $Install in
1)
    echo -e '\033[0;33mOffice installation has begun'
    sleep 2
    sudo yum update -y
    sudo yum upgrade -y
    sudo yum install -y wget
    sudo wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
    sudo tar zxpf luarocks-2.4.3.tar.gz
    cd luarocks-2.4.3
    sudo ./configure; sudo make bootstrap
    sudo make install
    sudo luarocks install luasocket
    sudo luarocks install luasec
    sudo luarocks install luautf8
    sudo luarocks install redis-lua
    sudo luarocks remove lua-cjson2
    sudo luarocks remove lua-cjson
    sudo yum install lua-cjson -y
    sudo luarocks install Lua-cURL
    cd ..
    sudo yum install tmux -y
    sudo yum install screen -y
    sudo yum install zip -y
    sudo yum install readline-devel libconfig-devel openssl-devel lua-devel make unzip git redis autoconf gcc-c++ jansson-devel python-devel expat-devel -y
    sudo yum install upstart -y
    sudo wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;sudo tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && sudo ./configure
    sudo make bootstrap
    sudo luarocks install luasocket
    sudo luarocks install luasec
    sudo luarocks install lua-term
    sudo luarocks install Lua-cURL
    sudo systemctl start redis.service
    sudo yum install -y libconfig++-devel
    sudo yum install -y libstdc++
    sudo yum install -y epel-release
    sudo yum install lua-lgi -y
    sudo yum install -y python3
    sudo yum install -y python3-pip
    sudo pip3 install yt-dlp
    sudo pip3 install ffmpeg
    sudo yum install -y ffmpeg
    sudo yum install -y gnome-calculator
    sudo pip3 install gtts
    sudo yum update -y
    cd ..
    sudo rm -rf luarocks*
    sudo unzip tdlua.zip
    sudo mv tdlua.so /usr/lib64/lua/5.1/tdlua.so
    sudo rm -fr tdlua.zip
    sudo lua Fast.lua
    ;;
2)
    echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
    sleep 2
    sudo unzip tdlua.zip
    sudo mv tdlua.so /usr/lib64/lua/5.1/tdlua.so
    sudo rm -fr tdlua.zip
    sudo lua Fast.lua
    ;;
esac
