#!/bin/bash

# Change directory to the script's location
cd "$(cd "$(dirname "$0")"; pwd)"

echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'

echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'

read Install

case $Install in
1)
    echo -e '\033[0;33mOffice installation has begun'
    sleep 2
    sudo apt-get update
    sudo apt-get install wget -y
    sudo wget https://luarocks.github.io/luarocks/releases/luarocks-2.4.3.tar.gz
    sudo tar zxpf luarocks-2.4.3.tar.gz
    cd luarocks-2.4.3
    sudo ./configure; sudo make bootstrap
    sudo make install
    sudo luarocks install luasocket
    sudo luarocks install luasec
    sudo luarocks install luautf8
    sudo luarocks install redis-lua
    sudo luarocks remove lua-cjson2
    sudo luarocks remove lua-cjson
    sudo apt-get install lua-cjson -y
    sudo luarocks install Lua-cURL
    cd ..
    sudo apt-get install tmux -y
    sudo apt-get install screen -y
    sudo apt-get install zip -y
    sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.1 liblua5.1-dev -y
    sudo apt-get install upstart -y
    sudo wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;sudo tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && sudo ./configure
    sudo make bootstrap
    sudo luarocks install luasocket
    sudo luarocks install luasec
    sudo luarocks install lua-term
    sudo luarocks install Lua-cURL
    sudo systemctl start redis-server
    sudo apt-get install libconfig++ -y
    sudo apt-get install libstdc++6 -y
    sudo apt-get install software-properties-common -y
    sudo apt-get install lua-lgi -y
    sudo apt-get install python -y
    sudo apt-get install python-pip -y
    sudo pip3 install yt-dlp
    sudo pip3 install ffmpeg
    sudo apt-get install ffmpeg -y
    sudo apt-get install gnome-calculator -y
    sudo pip3 install gtts
    sudo apt-get update -y
    cd ..
    sudo rm -rf luarocks*
    sudo wget https://github.com/ttahaa1/tory/raw/main/tdlua.zip
    sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.1/tdlua.so
    sudo lua Fast.lua
    ;;
2)
    echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
    sleep 2
    sudo wget https://github.com/ttahaa1/tory/raw/main/tdlua.zip
    sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.1/tdlua.so
    sudo lua Fast.lua
    ;;
esac
