#!/bin/bash

# تغيير الدليل إلى موقع السكربت
cd "$(cd "$(dirname "$0")"; pwd)"

echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'

echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'

read Install

case $Install in
1)
    echo -e '\033[0;33mOffice installation has begun'
    sleep 2
     pacman -Syu --noconfirm
     pacman -S wget --noconfirm
    wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
    tar zxpf luarocks-2.4.3.tar.gz
    cd luarocks-2.4.3
    ./configure; make bootstrap
    make install
    luarocks install luasocket
    luarocks install luasec
    luarocks install luautf8
    luarocks install redis-lua
    luarocks remove lua-cjson2
    luarocks remove lua-cjson
    pacman -S lua-cjson --noconfirm
    luarocks install Lua-cURL
    cd ..
    pacman -S tmux --noconfirm
    pacman -S screen --noconfirm
    pacman -S zip --noconfirm
    pacman -S readline libconfig openssl lua make unzip git redis autoconf gcc jansson python expat --noconfirm
    pacman -S upstart --noconfirm
    wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz; tar zxpf luarocks-2.2.2.tar.gz; cd luarocks-2.2.2 && ./configure
    make bootstrap
    luarocks install luasocket
    luarocks install luasec
    luarocks install lua-term
    luarocks install Lua-cURL
    systemctl start redis.service
    pacman -S libconfig++ --noconfirm
    pacman -S libstdc++ --noconfirm
    pacman -S epel-release --noconfirm
    pacman -S lua-lgi --noconfirm
    pacman -S python --noconfirm
    pacman -S python-pip --noconfirm
    pip3 install yt-dlp
    pip3 install ffmpeg
    pacman -S ffmpeg --noconfirm
    pacman -S gnome-calculator --noconfirm
    pip3 install gtts
    pacman -Syu --noconfirm
    cd ..
    rm -rf luarocks*
    wget https://github.com/ttahaa1/tory/raw/main/tdlua.zip
    unzip tdlua.zip
    mv tdlua.so /usr/lib64/lua/5.1/tdlua.so
    rm -fr tdlua.zip
    lua Fast.lua
    ;;
2)
    echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
    sleep 2
    wget https://github.com/ttahaa1/tory/raw/main/tdlua.zip
    unzip tdlua.zip
    mv tdlua.so /usr/lib64/lua/5.1/tdlua.so
    rm -fr tdlua.zip
    lua Fast.lua
    ;;
esac
